export const imageFilenames = [
  'Louisa_01.jpg',
  'Finland_01.jpg',
  'Finland_02.jpg',
  'Lisa_01.jpg',
  'Anseong_01.jpg',
  'Dagmar_01.jpg',
  'Louisa_02.jpg',
  'Finland_03.jpg',
  'Seoul_01.jpg',
  'Ahmad_01.jpg',
  'Rettungsdecke_01.jpg',
  'Khay_01.jpg',
  'Louisa_03.jpg',
  'Finland_04.jpg',
  'NewYork_01.jpg',
  'DMZ_01.jpg',
];
